name: Build & Smoke Test TrinityCore-Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub for private images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Get TrinityCore source
        run: ./action tc-fetch

      - name: Github Actions Cache Permissions Fix (pre cache download)
        run: |
          sudo chmod -R a+rwx .
          sudo chown -R $(whoami):$(id -ng) .

      - name: Cache / Retrieve pre-built TrinityCore
        uses: actions/cache@v2
        env:
          cache-name: trinitycore-build-cache
        with:
          path: containerfs/tc-server/source/build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./containerfs/tc-server/source/.git/HEAD') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List files to ensure cache is proper
        run: ls -laR .

      - name: Build TrinityCore
        run: ./action tc-build

      - name: Get DB
        run: ./action tc-db-fetch

      - name: Prepare maps
        run: ./ci/copy-maps-from-image

      - name: Boot services
        run: docker-compose up -f ./docker-compose.yaml -f ./ci/docker-compose.ci.yaml --exit-code-from trinitycore-ready

      - name: Github Actions Cache Permissions Fix (post build)
        run: |
          sudo chmod -R a+rwx .
          sudo chown -R $(whoami):$(id -ng) .

      # - name: Wait a bit and hopefully it loaded
      #   run: sleep 60

      # - name: Check containers
      #   run: docker-compose ps

      # - name: Dump docker logs
      #   run: docker-compose logs

      # - name: Check worldserver port
      #   run: nmap 0.0.0.0 -p 8085

      # - name: Check authserver port
      #   run: nmap 0.0.0.0 -p 3724

      # - name: Wait for final service (authserver)
      #   run: /bin/sh -c 'until curl -s "http://localhost:7777"; do sleep 1; done;'

      # - name: Shutdown services
      #   run: docker-compose down

      # - name: Upload logs
      #   if: always()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: TrinityCore Logs
      #     path: ./containerfs/tc-wd/*.log