name: Build & Smoke Test TrinityCore-Docker

on:
  push:
  pull_request:

jobs:
  build-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub for private images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Get TrinityCore Source
        run: ./action tc-fetch

      - name: Build TrinityCore
        run: ./action tc-build

      - name: Get DB
        run: ./action tc-db-fetch

      - name: Prepare maps
        run: ./ci/copy-maps-from-image

      - name: Boot Services
        run: docker-compose up -d

      - name: Wait (max 5minutes) for Final service (authserver)
        run: npx wait-port -t 300000 3724

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: TrinityCore Logs
          path: containerfs/tc-wd/*.log